version: '3'
services:
  elastic-1:
    build: .
    container_name: elastic-1
    ports:
    - "9200:9200"
    - "9300:9300"
    links:
    - elastic-2
  elastic-2:
    build: .
    container_name: elastic-2
    ports:
    - "9201:9200"
    - "9301:9300"
    environment:
      - reindex.remote.whitelist=elastic-1:9200
